services:
  mysql:
    image: mysql:8.0
    container_name: express_app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_app_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - "3301:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password --default-time-zone='-03:00'

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge